const http = require("http")
const fs = require("fs")
var mongoose = require('mongoose')
mongoose.connect('mongodb://127.0.0.1:27017/soltrace12',{useNewUrlParser: true, 
useUnifiedTopology: true,})
.then(()=>console.log("connection Successful......"))
.catch((err) => console.log(err))
// var db  = mongoose.connection;

// db.on('error',console.error.bind(console,'connection error:'));
// db.once('open',function(){
//     console.log("we are connected bro... to shashikart and you have successfully linked nodeJs with mongodb")
// })
var sold;
var solschema;
// creating document
const createdocument = async ()=>{
    try{
    solschema = new mongoose.Schema({
        S_No  : Number,
        Sun_X : Number,
        Sun_Y : Number,
        Sun_Z : Number,
        Ang : Number,
        Angle : Number,
        R_App_geom: String,
        R_App_dia: Number,
        R_Surf_geom: String,
        R_Surf_C1: Number,
        R_Surf_C2: Number,
        C_Pos_Z: Number,
        C_App_geom: String,
        C_App_dia: Number,
        C_Surf_geom: String,
        C_Surf_C1: Number,
        C_Surf_C2: Number,
        Avg_Flux: Number,
        T_hot:Number
      });
      sold = mongoose.model('sold', solschema);
    const soldat = [
      {
            "S_No": 1,
            "Angle": 0,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 90935.6,
            "T_hot": 1126.8111267111003
          },
          {
            "S_No": 2,
            "Angle": 0,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 383476,
            "T_hot": 1612.6236993068337
          },
          {
            "S_No": 3,
            "Angle": 0,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 10204700,
            "T_hot": 3662.676409199894
          },
          {
            "S_No": 4,
            "Angle": 0,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 310734,
            "T_hot": 1530.0149863186941
          },
          {
            "S_No": 5,
            "Angle": 0,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 57276,
            "T_hot": 1002.5168039532222
          },
          {
            "S_No": 6,
            "Angle": 0,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 157223,
            "T_hot": 1290.4093777008861
          },
          {
            "S_No": 7,
            "Angle": 0,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 1334850,
            "T_hot": 2202.706367548016
          },
          {
            "S_No": 8,
            "Angle": 0,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 1598590,
            "T_hot": 2304.2668065380262
          },
          {
            "S_No": 9,
            "Angle": 0,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 175113,
            "T_hot": 1325.647593843889
          },
          {
            "S_No": 10,
            "Angle": 0,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 863002,
            "T_hot": 1975.1561772153646
          },
          {
            "S_No": 11,
            "Angle": 0,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 390362,
            "T_hot": 1619.8148435175349
          },
          {
            "S_No": 12,
            "Angle": 0,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 81240,
            "T_hot": 1094.059570284484
          },
          {
            "S_No": 13,
            "Angle": 0,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 54471.9,
            "T_hot": 990.0146512175377
          },
          {
            "S_No": 14,
            "Angle": 0,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 137531,
            "T_hot": 1247.9541827253822
          },
          {
            "S_No": 15,
            "Angle": 0,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 1167660,
            "T_hot": 2130.235371000642
          },
          {
            "S_No": 16,
            "Angle": 0,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 1398370,
            "T_hot": 2228.455752779031
          },
          {
            "S_No": 17,
            "Angle": 0,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 311262,
            "T_hot": 1530.664523914319
          },
          {
            "S_No": 18,
            "Angle": 0,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 156027,
            "T_hot": 1287.9483004216913
          },
          {
            "S_No": 19,
            "Angle": 0,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 112301,
            "T_hot": 1186.299634707929
          },
          {
            "S_No": 20,
            "Angle": 0,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 80461.3,
            "T_hot": 1091.4284043331675
          },
          {
            "S_No": 21,
            "Angle": 0,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 55123.1,
            "T_hot": 992.960332034555
          },
          {
            "S_No": 22,
            "Angle": 0,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 121120,
            "T_hot": 1208.933622817167
          },
          {
            "S_No": 23,
            "Angle": 0,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 952383,
            "T_hot": 2024.423637028507
          },
          {
            "S_No": 24,
            "Angle": 0,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 1140550,
            "T_hot": 2117.7616182621427
          },
          {
            "S_No": 25,
            "Angle": 1,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 91315.9,
            "T_hot": 1126.5101049308
          },
          {
            "S_No": 26,
            "Angle": 1,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 381501,
            "T_hot": 1610.5433203791854
          },
          {
            "S_No": 27,
            "Angle": 1,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 9994520,
            "T_hot": 3643.6694903345533
          },
          {
            "S_No": 28,
            "Angle": 1,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 308667,
            "T_hot": 1527.4642027885714
          },
          {
            "S_No": 29,
            "Angle": 1,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 58505.4,
            "T_hot": 1007.8536640641241
          },
          {
            "S_No": 30,
            "Angle": 1,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 158225,
            "T_hot": 1292.4604635701799
          },
          {
            "S_No": 31,
            "Angle": 1,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 1340630,
            "T_hot": 2205.0869761382987
          },
          {
            "S_No": 32,
            "Angle": 1,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 1551970,
            "T_hot": 2287.2799408488204
          },
          {
            "S_No": 33,
            "Angle": 1,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 174181,
            "T_hot": 1323.8801963260373
          },
          {
            "S_No": 34,
            "Angle": 1,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 856226,
            "T_hot": 1971.267644451469
          },
          {
            "S_No": 35,
            "Angle": 1,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 385316,
            "T_hot": 1614.5546568365482
          },
          {
            "S_No": 36,
            "Angle": 1,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 94270.9,
            "T_hot": 1135.5150746481504
          },
          {
            "S_No": 37,
            "Angle": 1,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 56812.3,
            "T_hot": 1000.4815489556244
          },
          {
            "S_No": 38,
            "Angle": 1,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 143303,
            "T_hot": 1260.8467733462005
          },
          {
            "S_No": 39,
            "Angle": 1,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 1154520,
            "T_hot": 2124.216881696802
          },
          {
            "S_No": 40,
            "Angle": 1,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 1322500,
            "T_hot": 2197.5937484686015
          },
          {
            "S_No": 41,
            "Angle": 1,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 309948,
            "T_hot": 1529.046525998583
          },
          {
            "S_No": 42,
            "Angle": 1,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 201036,
            "T_hot": 1372.1985290071402
          },
          {
            "S_No": 43,
            "Angle": 1,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 112163,
            "T_hot": 1185.9350234322997
          },
          {
            "S_No": 44,
            "Angle": 1,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 78838.8,
            "T_hot": 1085.884145193554
          },
          {
            "S_No": 45,
            "Angle": 1,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 54975.9,
            "T_hot": 992.296770129639
          },
          {
            "S_No": 46,
            "Angle": 1,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 131839,
            "T_hot": 1234.8365219759935
          },
          {
            "S_No": 47,
            "Angle": 1,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 923086,
            "T_hot": 2008.6720283307525
          },
          {
            "S_No": 48,
            "Angle": 1,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 1032030,
            "T_hot": 2065.4827451849696
          },
          {
            "S_No": 49,
            "Angle": 2,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 94767.5,
            "T_hot": 1137.0075454462951
          },
          {
            "S_No": 50,
            "Angle": 2,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 378253,
            "T_hot": 1607.104385067095
          },
          {
            "S_No": 51,
            "Angle": 2,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 7756340,
            "T_hot": 3419.89443370726
          },
          {
            "S_No": 52,
            "Angle": 2,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 299137,
            "T_hot": 1515.5351876595507
          },
          {
            "S_No": 53,
            "Angle": 2,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 60131.9,
            "T_hot": 1014.786596710902
          },
          {
            "S_No": 54,
            "Angle": 2,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 163747,
            "T_hot": 1303.5924268962538
          },
          {
            "S_No": 55,
            "Angle": 2,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 1355170,
            "T_hot": 2211.0417108037673
          },
          {
            "S_No": 56,
            "Angle": 2,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 1409080,
            "T_hot": 2232.710441841857
          },
          {
            "S_No": 57,
            "Angle": 2,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 162098,
            "T_hot": 1300.2980309946213
          },
          {
            "S_No": 58,
            "Angle": 2,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 836595,
            "T_hot": 1959.8701886291778
          },
          {
            "S_No": 59,
            "Angle": 2,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 447832,
            "T_hot": 1676.3985308132633
          },
          {
            "S_No": 60,
            "Angle": 2,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 113832,
            "T_hot": 1190.3223341326895
          },
          {
            "S_No": 61,
            "Angle": 2,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 60257.1,
            "T_hot": 1015.31440392581
          },
          {
            "S_No": 62,
            "Angle": 2,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 157685,
            "T_hot": 1291.3563023157317
          },
          {
            "S_No": 63,
            "Angle": 2,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 1083250,
            "T_hot": 2090.6467864619017
          },
          {
            "S_No": 64,
            "Angle": 2,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 1086500,
            "T_hot": 2092.213131001955
          },
          {
            "S_No": 65,
            "Angle": 2,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 292335,
            "T_hot": 1506.8453923602337
          },
          {
            "S_No": 66,
            "Angle": 2,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 310806,
            "T_hot": 1530.1036083461338
          },
          {
            "S_No": 67,
            "Angle": 2,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 118348,
            "T_hot": 1201.956420161483
          },
          {
            "S_No": 68,
            "Angle": 2,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 75016.2,
            "T_hot": 1072.475194312264
          },
          {
            "S_No": 69,
            "Angle": 2,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 59350.6,
            "T_hot": 1011.4741060919647
          },
          {
            "S_No": 70,
            "Angle": 2,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 156075,
            "T_hot": 1288.0473447981167
          },
          {
            "S_No": 71,
            "Angle": 2,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 1003560,
            "T_hot": 2051.0881546094884
          },
          {
            "S_No": 72,
            "Angle": 2,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 1061630,
            "T_hot": 2080.1362692208963
          },
          {
            "S_No": 73,
            "Angle": 3,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 97464.1,
            "T_hot": 1145.011002832955
          },
          {
            "S_No": 74,
            "Angle": 3,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 410409,
            "T_hot": 1640.222291114498
          },
          {
            "S_No": 75,
            "Angle": 3,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 5617530,
            "T_hot": 3154.8944994627664
          },
          {
            "S_No": 76,
            "Angle": 3,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 394363,
            "T_hot": 1623.9495425336142
          },
          {
            "S_No": 77,
            "Angle": 3,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 62414.9,
            "T_hot": 1024.2844050729686
          },
          {
            "S_No": 78,
            "Angle": 3,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 189599,
            "T_hot": 1352.2515919645925
          },
          {
            "S_No": 79,
            "Angle": 3,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 1425780,
            "T_hot": 2239.2965984335715
          },
          {
            "S_No": 80,
            "Angle": 3,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 1518720,
            "T_hot": 2274.9293764562
          },
          {
            "S_No": 81,
            "Angle": 3,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 175838,
            "T_hot": 1327.0175748470115
          },
          {
            "S_No": 82,
            "Angle": 3,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 827768,
            "T_hot": 1954.6799090089871
          },
          {
            "S_No": 83,
            "Angle": 3,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 771819,
            "T_hot": 1920.7788153689994
          },
          {
            "S_No": 84,
            "Angle": 3,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 145686,
            "T_hot": 1266.0560870862614
          },
          {
            "S_No": 85,
            "Angle": 3,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 65476,
            "T_hot": 1036.6186685051593
          },
          {
            "S_No": 86,
            "Angle": 3,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 196368,
            "T_hot": 1364.1626983416336
          },
          {
            "S_No": 87,
            "Angle": 3,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 1549310,
            "T_hot": 2286.2992390567047
          },
          {
            "S_No": 88,
            "Angle": 3,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 1709030,
            "T_hot": 2343.073500826896
          },
          {
            "S_No": 89,
            "Angle": 3,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 280061,
            "T_hot": 1490.7734500969043
          },
          {
            "S_No": 90,
            "Angle": 3,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 516555,
            "T_hot": 1737.311255045854
          },
          {
            "S_No": 91,
            "Angle": 3,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 143216,
            "T_hot": 1260.6553630974993
          },
          {
            "S_No": 92,
            "Angle": 3,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 65141,
            "T_hot": 1035.2901835219452
          },
          {
            "S_No": 93,
            "Angle": 3,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 72000.1,
            "T_hot": 1061.5287616982732
          },
          {
            "S_No": 94,
            "Angle": 3,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 229782,
            "T_hot": 1418.8206218079993
          },
          {
            "S_No": 95,
            "Angle": 3,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 1850560,
            "T_hot": 2390.1451920160393
          },
          {
            "S_No": 96,
            "Angle": 3,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 2282150,
            "T_hot": 2518.7469484339786
          },
          {
            "S_No": 97,
            "Angle": 4,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 120042,
            "T_hot": 1206.2346407582672
          },
          {
            "S_No": 98,
            "Angle": 4,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 632332,
            "T_hot": 1827.4048823422365
          },
          {
            "S_No": 99,
            "Angle": 4,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 0,
            "T_hot": 0
          },
          {
            "S_No": 100,
            "Angle": 4,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 481767,
            "T_hot": 1707.2917939322906
          },
          {
            "S_No": 101,
            "Angle": 4,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 70579.7,
            "T_hot": 1056.2541852928389
          },
          {
            "S_No": 102,
            "Angle": 4,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 255379,
            "T_hot": 1456.7827367103419
          },
          {
            "S_No": 103,
            "Angle": 4,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 0,
            "T_hot": 0
          },
          {
            "S_No": 104,
            "Angle": 4,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 0,
            "T_hot": 0
          },
          {
            "S_No": 105,
            "Angle": 4,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 233240,
            "T_hot": 1424.128733641401
          },
          {
            "S_No": 106,
            "Angle": 4,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 863181,
            "T_hot": 1975.2585887565351
          },
          {
            "S_No": 107,
            "Angle": 4,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 412548,
            "T_hot": 1642.3552847758085
          },
          {
            "S_No": 108,
            "Angle": 4,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 133450,
            "T_hot": 1238.5916142036117
          },
          {
            "S_No": 109,
            "Angle": 4,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 78118,
            "T_hot": 1083.393610041321
          },
          {
            "S_No": 110,
            "Angle": 4,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 341203,
            "T_hot": 1566.2161614467582
          },
          {
            "S_No": 111,
            "Angle": 4,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 0,
            "T_hot": 0
          },
          {
            "S_No": 112,
            "Angle": 4,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 0,
            "T_hot": 0
          },
          {
            "S_No": 113,
            "Angle": 4,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 273593,
            "T_hot": 1482.090543237651
          },
          {
            "S_No": 114,
            "Angle": 4,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 626936,
            "T_hot": 1823.4938081359771
          },
          {
            "S_No": 115,
            "Angle": 4,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 58497,
            "T_hot": 1007.8174860932268
          },
          {
            "S_No": 116,
            "Angle": 4,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 47330.5,
            "T_hot": 955.8368372303736
          },
          {
            "S_No": 117,
            "Angle": 4,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 87402.1,
            "T_hot": 1114.2405453691724
          },
          {
            "S_No": 118,
            "Angle": 4,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 481447,
            "T_hot": 1707.0082183090128
          },
          {
            "S_No": 119,
            "Angle": 4,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 0,
            "T_hot": 0
          },
          {
            "S_No": 120,
            "Angle": 4,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 0,
            "T_hot": 0
          },
          {
            "S_No": 121,
            "Angle": 5,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 202899,
            "T_hot": 1375.366580689957
          },
          {
            "S_No": 122,
            "Angle": 5,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 0,
            "T_hot": 0
          },
          {
            "S_No": 123,
            "Angle": 5,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 0,
            "T_hot": 0
          },
          {
            "S_No": 124,
            "Angle": 5,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 0,
            "T_hot": 0
          },
          {
            "S_No": 125,
            "Angle": 5,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 87433.2,
            "T_hot": 1114.3396512774198
          },
          {
            "S_No": 126,
            "Angle": 5,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 0,
            "T_hot": 0
          },
          {
            "S_No": 127,
            "Angle": 5,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 0,
            "T_hot": 0
          },
          {
            "S_No": 128,
            "Angle": 5,
            "R_App_geom": "c",
            "R_App_dia": 0.2,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 0,
            "T_hot": 0
          },
          {
            "S_No": 129,
            "Angle": 5,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 356804,
            "T_hot": 1583.8203522940428
          },
          {
            "S_No": 130,
            "Angle": 5,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 0,
            "T_hot": 0
          },
          {
            "S_No": 131,
            "Angle": 5,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 0,
            "T_hot": 0
          },
          {
            "S_No": 132,
            "Angle": 5,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 101482,
            "T_hot": 1156.633442560145
          },
          {
            "S_No": 133,
            "Angle": 5,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 103613,
            "T_hot": 1162.6581837877723
          },
          {
            "S_No": 134,
            "Angle": 5,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 16550000,
            "T_hot": 4133.310109900224
          },
          {
            "S_No": 135,
            "Angle": 5,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 0,
            "T_hot": 0
          },
          {
            "S_No": 136,
            "Angle": 5,
            "R_App_geom": "c",
            "R_App_dia": 0.3,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 0,
            "T_hot": 0
          },
          {
            "S_No": 137,
            "Angle": 5,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 348868,
            "T_hot": 1574.9391347753756
          },
          {
            "S_No": 138,
            "Angle": 5,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 0,
            "T_hot": 0
          },
          {
            "S_No": 139,
            "Angle": 5,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 45573.8,
            "T_hot": 946.8415360744626
          },
          {
            "S_No": 140,
            "Angle": 5,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "s",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 0,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 29773.5,
            "T_hot": 851.2477235105608
          },
          {
            "S_No": 141,
            "Angle": 5,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.2,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 134266,
            "T_hot": 1240.4806765516807
          },
          {
            "S_No": 142,
            "Angle": 5,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.21,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 20210400,
            "T_hot": 4345.0243843469625
          },
          {
            "S_No": 143,
            "Angle": 5,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.22,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 0,
            "T_hot": 0
          },
          {
            "S_No": 144,
            "Angle": 5,
            "R_App_geom": "c",
            "R_App_dia": 0.4,
            "R_Surf_geom": "p",
            "R_Surf_C1": 2.22,
            "R_Surf_C2": 2.22,
            "C_Pos_Z": 0.23,
            "C_App_geom": "c",
            "C_App_dia": 0.03,
            "C_Surf_geom": "f",
            "C_Surf_C1": 0,
            "C_Surf_C2": 0,
            "Avg_Flux": 0,
            "T_hot": 0
          }
    ]

      soldat.forEach(async (data) => {
         const xyz = new sold(data); 
        const result = await xyz.save();
        // console.log(result);
      });
    }catch(err){
      console.log(err);
  }
}
createdocument();

// reading data
// const getDocument = async () =>{
//     try{
//     // const res = await sold.find();
//     const res = await sold.find()
//     .select({Sun_Y:0})

//     // res.json({
//     //   status : "success",
//     //   data : res,
//     // });
    
//     }catch(err){
//       // res.status(500).json({
//       //   status : "error",
//       // });
//         console.log(err);
//     }
// }
// getDocument();

const solds = new mongoose.model("solds",solschema);
module.exports = solds;
// create docs and insert

// connection with port starts
// const hostname = '127.0.0.1';
// const port = 3000;
// const home = fs.readFileSync('E:\\web_devlopment\\backend\\soltrace_tut\\home.hbs')
// const soltrace = fs.readFileSync('E:\\web_devlopment\\backend\\soltrace_tut\\Soltrace.hbs')

// const server = http.createServer((req,res)=>{
//     console.log(req.url);
//     url = req.url;
//     res.statusCode = 200;
//     res.setHeader('Content-Type', 'text/html');
//     // res.end(home);
//     if(url == '/'){
//         res.end(home);
//     }
//     else if(url == '/Soltrace'){
//         res.end(Soltrace);
//     }
//     else if(url == '/Services'){
//         res.end(Services);
//     }
//     else if(url == "/Contact"){
//         res.end(Contact);
//     }
    
// })

// server.listen(port, hostname, () => {
//     console.log(`Server running at http://${hostname}:${port}/`);
//   });